"""Add price_correction field to LineItem

Revision ID: 12bc7d076260
Revises: 56ee921ea014
Create Date: 2024-11-16 14:17:09.881708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bc7d076260'
down_revision = '56ee921ea014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_correction', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.drop_column('price_correction')

    # ### end Alembic commands ###
