"""Add PricebookItem table

Revision ID: 56ee921ea014
Revises: 58fac64d2f97
Create Date: 2024-11-15 14:46:57.975963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ee921ea014'
down_revision = '58fac64d2f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricebook_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('member_price', sa.Float(), nullable=False),
    sa.Column('add_on_price', sa.Float(), nullable=False),
    sa.Column('member_add_on_price', sa.Float(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.Column('deduct_as_job_cost', sa.Boolean(), nullable=False),
    sa.Column('allow_membership_discounts', sa.Boolean(), nullable=False),
    sa.Column('auto_replenish', sa.Boolean(), nullable=False),
    sa.Column('exclude_from_wizard', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricebook_item')
    # ### end Alembic commands ###
