"""Added fields for pricing discrepancies with approval

Revision ID: 9adcea3eb28a
Revises: e1ad8654a79b
Create Date: 2024-11-17 09:57:06.528678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adcea3eb28a'
down_revision = 'e1ad8654a79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discrepancy_action', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.drop_column('discrepancy_action')

    # ### end Alembic commands ###
