"""Add is_new field to PricebookItem

Revision ID: a1f6f734ebc1
Revises: 12bc7d076260
Create Date: 2024-11-16 14:19:38.794083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f6f734ebc1'
down_revision = '12bc7d076260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricebook_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('member_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('add_on_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('member_add_on_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('hours',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('vendor',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('taxable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('deduct_as_job_cost',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('allow_membership_discounts',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('auto_replenish',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('exclude_from_wizard',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricebook_item', schema=None) as batch_op:
        batch_op.alter_column('exclude_from_wizard',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('auto_replenish',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('allow_membership_discounts',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('deduct_as_job_cost',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('taxable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('vendor',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('hours',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('member_add_on_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('add_on_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('member_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
