"""Added new fields to LineItem

Revision ID: a2293bc0cda4
Revises: a1f6f734ebc1
Create Date: 2024-11-16 16:00:47.327371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2293bc0cda4'
down_revision = 'a1f6f734ebc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=31), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('member_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('add_on_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('member_add_on_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taxable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deduct_job_cost', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('membership_discount', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_replenish', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exclude_pricebook_wizard', sa.Boolean(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('found_in_pricebook')
        batch_op.drop_column('price_correction')
        batch_op.drop_column('vendor')
        batch_op.drop_column('part_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_number', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('vendor', sa.VARCHAR(length=100), server_default=sa.text("'UNKNOWN'"), nullable=False))
        batch_op.add_column(sa.Column('price_correction', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('found_in_pricebook', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=50), server_default=sa.text("'UNKNOWN'"), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('exclude_pricebook_wizard')
        batch_op.drop_column('auto_replenish')
        batch_op.drop_column('membership_discount')
        batch_op.drop_column('deduct_job_cost')
        batch_op.drop_column('taxable')
        batch_op.drop_column('hours')
        batch_op.drop_column('member_add_on_price')
        batch_op.drop_column('add_on_price')
        batch_op.drop_column('member_price')
        batch_op.drop_column('name')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
