"""Added missing fields to LineItem model

Revision ID: c588fbb927b1
Revises: a2293bc0cda4
Create Date: 2024-11-16 16:02:09.125285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c588fbb927b1'
down_revision = 'a2293bc0cda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('found_in_pricebook', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.drop_column('found_in_pricebook')
        batch_op.drop_column('part_number')
        batch_op.drop_column('vendor')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
