"""Added fields for pricing discrepancies

Revision ID: e1ad8654a79b
Revises: c588fbb927b1
Create Date: 2024-11-17 09:35:50.972872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ad8654a79b'
down_revision = 'c588fbb927b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pricebook_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discrepancy_resolved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_difference', sa.Float(), nullable=True))
        batch_op.drop_column('price')

    with op.batch_alter_table('pricebook_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_price', sa.Float(), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricebook_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('invoice_price')

    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('price_difference')
        batch_op.drop_column('discrepancy_resolved')
        batch_op.drop_column('pricebook_price')
        batch_op.drop_column('invoice_price')

    # ### end Alembic commands ###
